// Curated Material Icons set for IconPickerBtn.vue — same "hand-picked
// common subset, not the full ~2000-strong set" precedent as emojiList.js's
// EMOJI_CATEGORIES. Names (`n`) are ligature names from the bundled
// '@quasar/extras' material-icons webfont (see quasar.config.js's iconSet),
// the exact strings already typed by hand into block.icon/etc before this
// picker existed — this file doesn't change what's valid, just makes
// picking one not require memorizing/guessing the name. `k` carries French
// search keywords, same role as emojiList.js's own `k`.
export const ICON_CATEGORIES = [
  {
    name: 'navigation',
    icon: 'navigation',
    label: 'Navigation',
    items: [
      { n: 'home', k: 'accueil maison' },
      { n: 'apps', k: 'applications grille' },
      { n: 'menu', k: 'menu burger' },
      { n: 'search', k: 'recherche loupe' },
      { n: 'arrow_back', k: 'flèche retour' },
      { n: 'arrow_forward', k: 'flèche suivant' },
      { n: 'chevron_right', k: 'chevron droite' },
      { n: 'chevron_left', k: 'chevron gauche' },
      { n: 'expand_more', k: 'déplier bas' },
      { n: 'expand_less', k: 'replier haut' },
      { n: 'close', k: 'fermer croix' },
      { n: 'check', k: 'valider coche' },
      { n: 'add', k: 'ajouter plus' },
      { n: 'remove', k: 'retirer moins' },
      { n: 'more_vert', k: 'menu options verticales' },
      { n: 'more_horiz', k: 'menu options horizontales' },
      { n: 'refresh', k: 'actualiser recharger' },
      { n: 'tune', k: 'réglages filtres' },
      { n: 'filter_list', k: 'filtrer liste' },
      { n: 'sort', k: 'trier' },
    ],
  },
  {
    name: 'communication',
    icon: 'chat_bubble',
    label: 'Communication',
    items: [
      { n: 'chat_bubble', k: 'discussion bulle message' },
      { n: 'forum', k: 'forum discussion groupe' },
      { n: 'mail', k: 'mail email' },
      { n: 'send', k: 'envoyer' },
      { n: 'call', k: 'appel téléphone' },
      { n: 'call_end', k: 'raccrocher' },
      { n: 'videocam', k: 'vidéo caméra appel' },
      { n: 'mic', k: 'micro audio' },
      { n: 'mic_off', k: 'micro coupé muet' },
      { n: 'notifications', k: 'notification cloche' },
      { n: 'notifications_active', k: 'notification active cloche' },
      { n: 'notifications_off', k: 'notification désactivée' },
      { n: 'campaign', k: 'annonce mégaphone' },
      { n: 'contact_mail', k: 'contact courrier' },
      { n: 'alternate_email', k: 'arobase pseudo' },
      { n: 'link', k: 'lien url' },
      { n: 'share', k: 'partager' },
      { n: 'qr_code', k: 'qr code scanner' },
    ],
  },
  {
    name: 'people',
    icon: 'person',
    label: 'Personnes',
    items: [
      { n: 'person', k: 'personne profil' },
      { n: 'people', k: 'personnes groupe' },
      { n: 'group', k: 'groupe équipe' },
      { n: 'person_add', k: 'ajouter contact' },
      { n: 'person_remove', k: 'retirer contact' },
      { n: 'account_circle', k: 'compte profil avatar' },
      { n: 'face', k: 'visage' },
      { n: 'favorite', k: 'coeur aimer' },
      { n: 'favorite_border', k: 'coeur vide' },
      { n: 'thumb_up', k: 'pouce content aime' },
      { n: 'thumb_down', k: 'pouce baissé' },
      { n: 'star', k: 'étoile favori' },
      { n: 'star_border', k: 'étoile vide' },
      { n: 'verified', k: 'vérifié certifié badge' },
      { n: 'emoji_emotions', k: 'émoticône sourire' },
      { n: 'celebration', k: 'fête célébration' },
      { n: 'cake', k: 'gâteau anniversaire' },
    ],
  },
  {
    name: 'finance',
    icon: 'account_balance_wallet',
    label: 'Finance & commerce',
    items: [
      { n: 'account_balance', k: 'banque institution' },
      { n: 'account_balance_wallet', k: 'portefeuille solde' },
      { n: 'attach_money', k: 'argent dollar' },
      { n: 'euro_symbol', k: 'euro argent' },
      { n: 'payments', k: 'paiement' },
      { n: 'credit_card', k: 'carte bancaire' },
      { n: 'receipt', k: 'reçu facture' },
      { n: 'receipt_long', k: 'reçu détaillé relevé' },
      { n: 'savings', k: 'épargne économies tirelire' },
      { n: 'trending_up', k: 'tendance hausse graphique' },
      { n: 'trending_down', k: 'tendance baisse graphique' },
      { n: 'bar_chart', k: 'graphique barres statistiques' },
      { n: 'pie_chart', k: 'graphique camembert statistiques' },
      { n: 'shopping_cart', k: 'panier achat' },
      { n: 'shopping_bag', k: 'sac achat' },
      { n: 'store', k: 'boutique magasin' },
      { n: 'local_offer', k: 'promo étiquette prix' },
      { n: 'card_giftcard', k: 'cadeau' },
      { n: 'work', k: 'travail emploi mallette' },
      { n: 'inventory_2', k: 'inventaire boîte stock' },
    ],
  },
  {
    name: 'media',
    icon: 'image',
    label: 'Médias & fichiers',
    items: [
      { n: 'image', k: 'image photo' },
      { n: 'photo_camera', k: 'appareil photo' },
      { n: 'videocam', k: 'vidéo caméra' },
      { n: 'music_note', k: 'musique note' },
      { n: 'headphones', k: 'écouteurs casque audio' },
      { n: 'play_arrow', k: 'lecture jouer' },
      { n: 'pause', k: 'pause' },
      { n: 'folder', k: 'dossier' },
      { n: 'insert_drive_file', k: 'fichier document' },
      { n: 'description', k: 'document texte' },
      { n: 'attach_file', k: 'pièce jointe trombone' },
      { n: 'download', k: 'télécharger' },
      { n: 'upload', k: 'envoyer fichier' },
      { n: 'edit', k: 'éditer crayon modifier' },
      { n: 'delete', k: 'supprimer poubelle' },
      { n: 'save', k: 'enregistrer disquette' },
      { n: 'bookmark', k: 'marque-page favori' },
      { n: 'label', k: 'étiquette tag' },
    ],
  },
  {
    name: 'status',
    icon: 'info',
    label: 'Statuts & alertes',
    items: [
      { n: 'info', k: 'information' },
      { n: 'warning', k: 'avertissement attention' },
      { n: 'error', k: 'erreur' },
      { n: 'help', k: 'aide question' },
      { n: 'check_circle', k: 'validé coche cercle succès' },
      { n: 'cancel', k: 'annulé croix cercle' },
      { n: 'block', k: 'bloqué interdit' },
      { n: 'lock', k: 'verrouillé cadenas' },
      { n: 'lock_open', k: 'déverrouillé cadenas ouvert' },
      { n: 'visibility', k: 'visible oeil' },
      { n: 'visibility_off', k: 'invisible oeil barré' },
      { n: 'flag', k: 'drapeau signaler' },
      { n: 'priority_high', k: 'priorité important' },
      { n: 'schedule', k: 'horloge programmé' },
      { n: 'hourglass_empty', k: 'sablier attente' },
      { n: 'battery_full', k: 'batterie pleine' },
      { n: 'wifi', k: 'wifi réseau' },
      { n: 'signal_cellular_alt', k: 'signal réseau mobile' },
    ],
  },
  {
    name: 'places',
    icon: 'place',
    label: 'Lieux & objets',
    items: [
      { n: 'place', k: 'lieu localisation épingle' },
      { n: 'map', k: 'carte plan' },
      { n: 'directions_walk', k: 'marche pas podomètre' },
      { n: 'directions_car', k: 'voiture trajet' },
      { n: 'flight', k: 'avion vol voyage' },
      { n: 'restaurant', k: 'restaurant repas' },
      { n: 'local_cafe', k: 'café boisson' },
      { n: 'hotel', k: 'hôtel logement' },
      { n: 'school', k: 'école étude' },
      { n: 'sports_esports', k: 'jeu vidéo manette' },
      { n: 'fitness_center', k: 'sport musculation' },
      { n: 'pets', k: 'animal patte' },
      { n: 'wb_sunny', k: 'soleil beau temps' },
      { n: 'cloud', k: 'nuage météo' },
      { n: 'water_drop', k: 'eau pluie goutte' },
      { n: 'settings', k: 'réglages paramètres' },
      { n: 'build', k: 'outils clé' },
      { n: 'security', k: 'sécurité bouclier' },
    ],
  },
]

export const ALL_ICONS = ICON_CATEGORIES.flatMap((cat) => cat.items)
